### ISSUE TITLE
Self-contained C# shared library using DNNE

### ISSUE THREAD

**Issue by ramikhaldi** [AaronRobinsonMSFT/DNNE#131]
Hi,

I have issues when trying to have a self contained shared library for a project using DNNE. The error I get (in runtime, build is successful)
`Initialization for self-contained components is not supported.`

Does anybody have a successful self-contained run ?

Thanks,
KR

Rami

**Comment by AaronRobinsonMSFT** [comment]
@ramikhaldi The self-contained scenario is complex and not something I am exposing as a top-level scenario. In order to start down this path, please see the following:

https://github.com/AaronRobinsonMSFT/DNNE/blob/c2feaa898fe35587f6e5f692809dac05ce44e856/src/msbuild/DNNE.props#L87-L93

People have been successful with self-contained and DNNE but, as mentioned, it is complicated to set up and isn't a first class scenario for .NET class libraries.

**Comment by ramikhaldi** [comment]
@AaronRobinsonMSFT  Thanks for your response. I switched the DnneSelfContained_Experimental flag to true and modified the  runtimeconfig.json and deps.json files to point to correct frameworks/versions. The problem is that the runtime was still searching for globally installed .net libraries.  Adjusting the DOTNET_ROOT and DOTNET_MULTILEVEL_LOOKUP did not seem to help there. 
The interesting thing is, that I could run a small self-contained app without DNNE successfully, but as soon the DNNE comes into place, I get the issue. Could you please provide a very small example how it works  (without any pre-installed .net runtimes) ?
