### ISSUE TITLE
Error MSB3073: The command ""clang" -g -O0 -shared -fpic -D DNNE_ASSEMBLY_NAME=Brand.Company.Engine -D DNNE_COMPILE_AS_SOURCE -I 

### ISSUE THREAD

**Issue by A-BEECHEY** [AaronRobinsonMSFT/DNNE#136]
I am trying to generate .so files from a .NET c# Visual Studio project

when I build my project I get these two build errors

```
/Users/user/github/my-dotnet-project/libraries/dotnet/Company.Engine/src/clang: Error: no such file or directory: '/Users/user/github/my-dotnet-project/libraries/dotnet/Company.Engine/src/obj/Debug/netstandard2.1/dnne/Brand.Company.Engine.g.c' (Company.Engine)

/Users/user/.nuget/packages/dnne/1.0.32/build/DNNE.targets(5,5): Error MSB3073: The command ""clang" -g -O0 -shared -fpic -D DNNE_ASSEMBLY_NAME=Brand.Company.Engine -D DNNE_COMPILE_AS_SOURCE -I "/Users/user/.nuget/packages/dnne/1.0.32/tools/platform" -I "/usr/local/share/dotnet/packs/Microsoft.NETCore.App.Host.osx-x64/6.0.9/runtimes/osx-x64/native" -o "/Users/user/github/my-dotnet-project/libraries/dotnet/Company.Engine/src/obj/Debug/netstandard2.1/dnne/bin/Brand.Company.EngineNE.dylib" "/Users/user/github/my-dotnet-project/libraries/dotnet/Company.Engine/src/obj/Debug/netstandard2.1/dnne/Brand.Company.Engine.g.c" "/Users/user/.nuget/packages/dnne/1.0.32/tools/platform/platform.c" -lstdc++ "/usr/local/share/dotnet/packs/Microsoft.NETCore.App.Host.osx-x64/6.0.9/runtimes/osx-x64/native/libnethost.a" " exited with code 1. (MSB3073) (Company.Engine)
```

I am new to Visual Studio, c#, .NET.

I am attempting to generate .so files to enable me to use the .NET dll in an Android application.

I have two questions

1). How do I fix the above build errors
2). Can DNNE generate usable .so files from .NET c# .dll's

**Comment by AaronRobinsonMSFT** [comment]
@A-BEECHEY Sorry you are hitting this issue. The problem here is typically one needs to be build native code on the target platform. In this case, .NET can be build on X and used on Y, but for say a C application if I want to run it on Y platform, I need to build it on a Y compatible platform or have the Y platform's native tool chain available on platform X during build. This was also asked in https://github.com/AaronRobinsonMSFT/DNNE/issues/84.

There are cross-platform native compilers and someone did suggestion using one in https://github.com/AaronRobinsonMSFT/DNNE/issues/128. This is going to require a fair bit of work and testing though so I've not put a lot of time into it yet.

> I am attempting to generate .so files to enable me to use the .NET dll in an Android application.

I highly recommend looking at https://github.com/xamarin/java.interop or the Xamarin Android offerings for this scenario.

**Comment by A-BEECHEY** [comment]
@AaronRobinsonMSFT thanks for taking the time to respond to my issue/question. Unless i have lost the plot on `java.interop` i do not think that will solve my issue. My current use case is that i have `c#`(`.dll`) files that cannot be changed as they are certificated medical engines that we would like to call from a native Android `Kotlin`/`Java` application. currently the `.dll` are developed in `.NET5`. from the link you provided it appears `java.interop` is only available in .NET7 and from my quick reading of the docs it sounds like we have to amend our existing c# code to use `java.interop`.

**Comment by AaronRobinsonMSFT** [comment]
@A-BEECHEY Please let me know if you are still hitting issues.
