### ISSUE TITLE
How could one use async functions?

### ISSUE THREAD

**Issue by ThaDaVos** [AaronRobinsonMSFT/DNNE#171]
In my current project, the need has come to call async methods from other libraries - any guidance if we can mark the exported method as async? Or should one simply follow the default "calling async from sync" practices inside C#?

**Comment by AaronRobinsonMSFT** [comment]
The async model is merely a syntactic sugar state machine around the classic callback mechanism. There is integration with the .NET thread-pool and a bit of clever magic going on but it all boils down to callbacks. In this case the Roslyn compiler generates a large callback state machine and there is no simple way to express that across the interop boundary. The C++ language has `co_await`, which represents a similar state machine approach but reconciling them would be tough and is definitely beyond the scope of DNNE since its primary contract is C. 

> Or should one simply follow the default "calling async from sync" practices inside C#?

This is correct. One could accept a callback in the signature exported function signature and handle the state machine transition, but that would really achieve the semantics I assume being expected on the other side of the boundary.
