### ISSUE TITLE
Delphi 6 - WPF stability issues

### ISSUE THREAD

**Issue by mterwoord** [AaronRobinsonMSFT/DNNE#194]
I've been using DNNE for a few years now, embedding .NET (6-8) in a Delphi 6 project. Works like a charm.

Last year or so, some of my users are complaining about vague stability issues. Random freezes and weird errors:
1. ComException UCEERR_RENDERTHREADFAILURE  (0x88980406)
2. Not enough quota to process this command
3. Similar ones

I checked the app with a profiler, and also checked by taking snapshots of the running process and see what the state was. Nothing popped up.

Is there anything you can advice in this regard?

The process is marked with the Large Address Aware bit.

I recently have been thinking, maybe I should use GC.AddMemoryPressure to add the native app's memory pressure for the GC to take into account. 

Any suggestions are greatly appreciated!

**Comment by AaronRobinsonMSFT** [comment]
@mterwoord This sounds rough. Let's try to narrow this down.

1) What OS is this being run on? 
2) What is the bitness of the process?
3) It sounds like WPF is being hosted in a Delphi app, or is it the other way around?
4) Have you been able to reproduce this locally?

> The process is marked with the Large Address Aware bit.

This makes it sound like 32-bit is involved.

> I recently have been thinking, maybe I should use GC.AddMemoryPressure to add the native app's memory pressure for the GC to take into account.

Not a a bad idea in general. All this is going to do though is trigger a GC more regularly. It can be simulated just by calling `GC.Collect()` in opportune placed.

> I've been using DNNE for a few years now, embedding .NET (6-8) in a Delphi 6 project. Works like a charm.

Were you previously using .NET Framework and not seeing these issues?

> Last year or so, some of my users are complaining about vague stability issues. Random freezes and weird errors:

This sounds like one or more of the following interactions:

* GC Regions - .NET 6 or 7? The [mem-doc](https://github.com/Maoni0/mem-doc) will help how to investigate this dimension.
* Some OS rendering update
* Minor WPF update - unlikely as there have been few changes due to concerns about destabilizing the platform.

**Comment by mterwoord** [comment]
Feeling kind of stupid now. Turned out the issues were related to good-old memory leaks. 

I've been gradually adding more and more telemetry to the product, and I found that GDI/USER object count of the processes increased towards the 10,000 (which is the default limit). Investigation with dotMemory showed me that there were WPF windows not being garbage collected. I fixed those 2 weeks ago, and my customers didn't have any freezes since. 

Thanks for taking the time answering my questions. I will be closing this ticket.
