### ISSUE TITLE
Failed for paths with ( ) symbols

### ISSUE THREAD

**Issue by mikasoukhov** [AaronRobinsonMSFT/DNNE#50]
For proj files with special characters task fails.

**Comment by AaronRobinsonMSFT** [comment]
This is due to an interesting property of the `ITaskItem` in MSBuild. Details on why this is occurring can be found in source for [`TaskItem.ItemSpec`](https://github.com/dotnet/msbuild/blob/40beb5a025fb18c82a159f407b5ce2383531a8eb/src/Build/Instance/ProjectItemInstance.cs#L861-L886) and [`TaskItem.ToString`](https://github.com/dotnet/msbuild/blob/40beb5a025fb18c82a159f407b5ce2383531a8eb/src/Build/Instance/ProjectItemInstance.cs#L1154-L1160).

Thanks for reporting this issue.

**Comment by AaronRobinsonMSFT** [comment]
@mikasoukhov I will include this fix the next time I publish a package. Are you blocked by this issue or can it wait?
