### ISSUE TITLE
x86 provides export functions with @2 names

### ISSUE THREAD

**Issue by mikasoukhov** [AaronRobinsonMSFT/DNNE#52]
For x64 export is well. For x86 exports provides function_name@2 for all functions.

**Comment by AaronRobinsonMSFT** [comment]
@mikasoukhov My original intent here was to consider this behavior as "by-design". I am assuming it is only observed on Windows since the default export calling convention on Windows-x86 is `stdcall` - non-Windows the default is `cdecl`. Using the [`UnmanagedCallersOnly.CallConvs`](https://docs.microsoft.com/dotnet/api/system.runtime.interopservices.unmanagedcallersonlyattribute.callconvs) property one can override this default. Using [`CallConvCdecl`](https://docs.microsoft.com/dotnet/api/system.runtime.compilerservices.callconvcdecl) would address the issue; however, if `stdcall` is desired then we may need to consider other options.

On Windows, `stdcall` isn't common on non-Windows in my experience, MSVC decorates the export as defined [here](https://docs.microsoft.com/cpp/build/reference/decorated-names#FormatC). There are ways default decoration can be overridden as defined [here](https://docs.microsoft.com/cpp/build/reference/export-exports-a-function#remarks) and I am more than willing to expose hooks to accomplish this (e.g. user supplied `.def` file). I don't know if GCC/Clang decorate `stdcall` in the same way, but it is possible.

As mentioned, my gut reaction is that this is "by-design" but I do appreciate the expectation of the "EntryPoint" contract. My biggest concern with attempting to properly support this is that DNNE would need to compute the anticipated export when using `stdcall` and although that is likely straight forward I am sure there are corner cases to be missed and cause more grief. Ideally one would always avoid using `stdcall` and defer to `cdecl` on x86 or be comfortable with supplying a `.def` file on Windows.

Do you have a strong opinion in this case?

**Comment by mikasoukhov** [comment]
1) I am mentioned Windows x86.
2) I am not familiar with C++ and my report was related about DNNE. Generated assembly not work with x86 unmanaged apps.

**Comment by AaronRobinsonMSFT** [comment]
@mikasoukhov Thanks for the additional context. My recommendation then is to update your exports to define the `cdecl` calling convention. For example:

```CSharp
[UnmanagedCallersOnly(CallConvs = new []{typeof(System.Runtime.CompilerServices.CallConvCdecl)})]
```

I will update the documentation with details about this issue and the appropriate mitigation.

**Comment by netcorefan1** [comment]
Hello,
first of all I want to congratulate with the author. This is the only library that got me up and running.
Unfortunately I am experiencing the same issue reported from @mikasoukhov.
I am trying to build two separate x86 and x64 dll. 
x64 compiles fine, but the x86 fails with the following errors:
`Error LNK2019: unresolved external symbol _get_hostfxr_path@12 referenced in function _load_hostfxr`
Even if I export with `[UnmanagedCallersOnly(CallConvs = new []{typeof(System.Runtime.CompilerServices.CallConvCdecl)})]` it still fails with the same error.
The project is a simple .Net 5 library containing the following function:
```
[UnmanagedCallersOnly()]
public static int Run(IntPtr parameters)
{
      return 0;
}
```
I am only interested in Windows 10, but I also need x86 architecture working.
I am running the latest VS2019 with the latest Windows SDK available in its installer (19041).
May be I'm missing something obvious, but after looking the documentation for hours without understanding what I am doing wrong I have no other choice than ask for help.
Many thanks
