### ISSUE TITLE
Blittable structures

### ISSUE THREAD

**Issue by mikasoukhov** [AaronRobinsonMSFT/DNNE#55]
Are they supported yet? Seems Generator do not provide any way to reflect any complex types even they are blittable.

**Comment by AaronRobinsonMSFT** [comment]
@mikasoukhov This is supported to some degree. However it does require using `C99TypeAttribute` - discussed [here](https://github.com/AaronRobinsonMSFT/DNNE#native-code-customization). This doesn't change the limitations on the declaration of the C# type signature though.

The point of DNNE is to provide the absolute minimal native export. A consequence of this is that C# signatures must be only of [unmanaged types](https://docs.microsoft.com/dotnet/csharp/language-reference/builtin-types/unmanaged-types) that are also blittable. The C# language doesn't define blittability though - that is a runtime construct. This is why supporting `MarshalAs` and the rest of those interop types isn't supported - it isn't obvious how users would like to express types in native code and avoiding any marshalling is a specific design goal of DNNE. It is a low level building block that is avoiding the built-in system's limitations and servicing issues.

**Comment by andreispark** [comment]
Hello @AaronRobinsonMSFT 

This tool is working very well, I thank you for your efforts towards improving it and for making it in the first place. I have a question regarding the blittable structures.

If I export a function that takes a parameter in the function signature (that has a type of int, byte, etc) the function is exported correctly and everything works as intended. I did notice however that adding a byte[] or int[] as a parameter in my function signature appears to not be a supported DNNE type.
"Error	CS8894	Cannot use 'int[]' as a parameter type on a method attributed with 'UnmanagedCallersOnly'.	DeepArmor.SDK.Interface (net5.0)	C:\... \CppExample.cs"

I have gotten around this by using an int* which also works as intended given that the C++ memory allocation is done correctly. I was under the impression that one-dimensional arrays of a blittable type are in fact also blittable, so I was wondering if perhaps this is not yet supported in the DNNE tool. I was also able to pass  in a struct as you have shown in your MiscExample.cs file

Regards, and have a nice holiday.

**Comment by AaronRobinsonMSFT** [comment]
> I was under the impression that one-dimensional arrays of a blittable type are in fact also blittable, so I was wondering if perhaps this is not yet supported in the DNNE tool.

@andreispark I assume the above impression was taken from [here](https://docs.microsoft.com/dotnet/framework/interop/blittable-and-non-blittable-types) based on the following:

>The following complex types are also blittable types:
> * One-dimensional arrays of blittable types, such as an array of integers. However, a type that contains a variable array of blittable types is not itself blittable.

I will update the documentation to indicate that arrays are not supported in any way. The array type is special cased in the CLR and requires far more support than is first assumed based on the above statement. This concept has come up multiple times recently so let me try to clarify the idea behind the generated exports.

The DNNE tool at first glance appears designed to provide native exports to any public static managed function. This is only partially true and for cases when true has many qualifiers that will become apparent momentarily. Additionally it is designed to expose native function that have the lowest possible overhead for consumption by a native environment. Traditionally, exposure of single managed functions to native code is done through what is called a Reverse P/Invoke - marshal a `Delegate` to native code as a callable function pointer. This marshalling appears simple but has extensive operational and memory overhead to make it "just work". The "just work" side of things is actually simple for all blittable types but not special types like arrays mentioned above. Consider the following example:

```C#
delegate int SumDelegate(int[] a);
static int Sum(int[] a) { ... }
```

```C
// A function that returns the function pointer
// to the managed function.
void* GetSumFunction();
void NativeSum()
{
  ...
  typedef int(*SumFptr)(int*);
  SumFptr fptr = (SumFptr)GetSumFunction();
  int a[] = {...};
  int sum = fptr(a);
  ...
}
```

The signature of the managed `Delegate` states an `int[]`, but that doesn't mean that on the C side it is the same signature. One can make that happen using [`MarshalAsAttribute`](https://docs.microsoft.com/dotnet/api/system.runtime.interopservices.marshalasattribute) and adorn the managed function with these details. However, code to respect these details must be generated at run time by the CLR in order to convert the C `int*` into a C# `int[]` - that is where the `Delegate` comes in and that hides a lot of work. The above call stack would look like:

```
- NativeSum()
  - Generated_Delegate_For_Sum(int* a) <- Converts C-int* into C#-int[]
    - Sum(int[] a)
```

When using DNNE and [`UnmanagedCallersOnlyAttribute`](https://docs.microsoft.com/dotnet/api/system.runtime.interopservices.unmanagedcallersonlyattribute), the expectation is one doesn't want that extra overhead of the `Delegate`. DNNE is providing the most efficient way to get from native to managed code with the least amount of overhead possible. The above C# should then be updated to the following:

```C#
[UnmanagedCallersOnly]
unsafe static int Sum(int* a) { /* Conver a to a C# array or use Span<int> */ ... }
```

The stack at run time is then the following with the absolute minimum of overhead possible given CLR constraints (e.g. Garbage Collection).

```
- NativeSum()
  - Sum(int* a)
```

**Comment by andreispark** [comment]
Hello @AaronRobinsonMSFT 

Thank you for providing such a detailed response. This makes sense, I will try this out.

I hope you had a great start to this new year.
