### ISSUE TITLE
Add support for ARM64 on Windows

### ISSUE THREAD

**Issue by AaronRobinsonMSFT** [AaronRobinsonMSFT/DNNE#6]
At present only `x86` and `x64` are supported.

https://github.com/AaronRobinsonMSFT/DNNE/blob/ac4c203ea120ec0193639ed89a37a791e8201231/src/msbuild/DNNE.BuildTasks/Windows.cs#L45-L47

Would also need to update the query for what VC Tools components are installed:

https://github.com/AaronRobinsonMSFT/DNNE/blob/ac4c203ea120ec0193639ed89a37a791e8201231/src/msbuild/DNNE.BuildTasks/Windows.cs#L164

**Comment by AaronRobinsonMSFT** [comment]
Updating the title since ARM support on Windows is [being dropped for .NET 5](https://github.com/dotnet/core/blob/master/release-notes/5.0/5.0-supported-os.md).

**Comment by AaronRobinsonMSFT** [comment]
Visual Studio components for ARM64 tooling is `Microsoft.VisualStudio.Component.VC.Tools.ARM64`

Windows SDK discovery for ARM64 would also need to be updated.

**Comment by bambache** [comment]
Hi @AaronRobinsonMSFT ! Thank you for your great work!
I have reached this project while searching for a way to have exports from an unmanaged library (which implements a WPF UI).
I have tried UnmanagedExports and DLLExports, which worked great on .NET framework 4.0, but turns out we need to also support ARM64. Knowing the .NET 5 runtime introduced support for ARM64, I have migrated the library.
So, I think, cross-targeting would be my primary scenario, as I would use an x64 ( still most ubiquitous ) to compile binaries for ARM64.
Do you have any plan for finishing up this issue on the horizon?

**Comment by AaronRobinsonMSFT** [comment]
>Do you have any plan for finishing up this issue on the horizon?

@bambache Thanks for reaching out. This shouldn't be a lot of work, I was simply waiting for someone to ask for it :-) If ARM64 will provide value I can look into this next. I have a few other higher priority tasks but can make this a priority when I come back to DNNE. Appreciate you letting me know the need.

**Comment by bambache** [comment]
Thanks @AaronRobinsonMSFT , this is great news. I'll keep my eyes open for any updates.

**Comment by AaronRobinsonMSFT** [comment]
@bambache I will push out a new package this weekend. I tested the building of ARM64 through the use of the RID and was able to build locally. Is that also your build process?

**Comment by bambache** [comment]
Hey @AaronRobinsonMSFT , thank you so much for your quick response in addressing this issue!
I have tried it locally and it builds without issues. I think this is what we'll use as the build process.
