### ISSUE TITLE
Order of exported functions

### ISSUE THREAD

**Issue by gimi87** [AaronRobinsonMSFT/DNNE#63]
Hello,

I'm trying to use my library with your solution.
In the "Dll Export Viewer" application I can see that all methods are exported... but... in asceding order.
In the code, I have the correct order of methods (by the number of line).

This is my library:
![1](https://user-images.githubusercontent.com/22730088/108077579-f7bbf000-706c-11eb-9e40-0cbe1e2a79ec.png)

And this is 3rd party library:
![2](https://user-images.githubusercontent.com/22730088/108077621-00acc180-706d-11eb-8e8d-681a5e46c716.png)

I want order from the second image. By the "Ordinal" value.
Is this possible in your library? :)
And can I somehow remove these 3 last methods? :)

**Comment by AaronRobinsonMSFT** [comment]
> I want order from the second image. By the "Ordinal" value.
> Is this possible in your library? :)

@gimi87 At present no, but this is technically possible. I just need to think about the best way to expose this. Is this a blocking scenario?

> And can I somehow remove these 3 last methods? :)

That would be a bit more complicated but it is technically possible to remove at least 2 of them. I can remove the two that DNNE adds but `get_hostfxr_path()` isn't something I can easily control as it comes from a linked in static lib.

**Comment by AaronRobinsonMSFT** [comment]
@gimi87 In order to enable this there are a few options.

1) Allow users to provide a [`.def`](https://docs.microsoft.com/cpp/build/reference/exports) file on Windows to specify the ordinal value as well as all other export features.
1) DNNE could generate a `.def` file through a series of attributes.
1) Permit the user to provide compiler flags (e.g. [`/export`](https://docs.microsoft.com/cpp/build/reference/export-exports-a-function))

To be quite honest I am likely to opt for (1). Will this work for you? 

A follow up, how was the desired binary built originally? Is it also managed or is it a native binary attempting to be replaced with a managed implementation?

**Comment by gimi87** [comment]
This is not blocking. I just tried your solution as it works in NET5. My project worked fine in .NET Framework with another dll export solution. Since I moved everything to NET5 I am looking for a solution. I was curious if this DNNE would work. I'm very close now.

Currently 3rd party application (which I use to test dll export) does not even load library exported by DNNE. Maybe because the order of the functions is wrong.

If you will have some time to develop. Remember to (perhaps) provide an appropriate option to keep order :)

**Comment by AaronRobinsonMSFT** [comment]
@gimi87 I don't control the order unfortunately. This is dictated by the MSVC linker - which by default is alphabetical. One can manually dictate the ordinal values using the `.def` or `/exports` but that isn't something I can know. In this case it would appear the previous tooling used defined their own order and now we are in a pickle. All of the proposed solutions will "solve" the problem but the issue is the order isn't obvious and as such would need users to either adorn the exports with numbers _or_ provide a `.def` that states the ordinal values. Either way the user would need to state their preferred order.

**Comment by AaronRobinsonMSFT** [comment]
@gimi87 I've added support for providing a `.def` file. This will enable you to expose and order all native exports controlled by DNNE. The one function that is not controllable is `get_hostfxr_path()`, but all others can be updated however is deemed appropriate.

See [Exporting details](https://github.com/AaronRobinsonMSFT/DNNE#exporting-details).
